version: '3'
services:
  #################################################  
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/raspberrypi4-64-homeassistant:2023.4.6 # Must be full version on this image for some reason, not just year.month
    network_mode: host
    environment:
      - TZ=Europe/Oslo
    volumes:
      - /home/minus/homeassistant_config:/config
  #################################################
  obd:
    container_name: obd
    restart: unless-stopped
    network_mode: host
    devices:
      - '/dev/serial/by-id/usb-ScanTool.net_LLC_OBDLink_SX_113011164450-if00-port0:/dev/obd'
    environment:
      - TZ=Europe/Oslo
    build:
      context: ./obd
      dockerfile: Dockerfile
    env_file:
      - secrets.env
  #################################################
  code-server:
    container_name: code-server
    restart: unless-stopped
    image: lscr.io/linuxserver/code-server
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - DEFAULT_WORKSPACE=/dockervolumes
    volumes:
      - '/home/minus/homeassistant_config:/dockervolumes/homeassistant_config'
  #################################################
