version: '3'
services:
  #################################################  
  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: homeassistant/raspberrypi4-64-homeassistant:2022.8.6 # Must be full version on this image for some reason, not just year.month
    environment:
      - TZ=Europe/Oslo
    volumes:
      - /home/minus/homeassistant_config:/config
      - /home/minus/logs:/logs
      - '/run/dbus:/run/dbus:ro'
    ports:
      - '8123:8123'
    networks:
      - minusnet
  #################################################
  obd:
    container_name: obd
    restart: unless-stopped
    #devices:
    #  - '/dev/serial/by-id/usb-ScanTool.net_LLC_OBDLink_SX_113011164450-if00-port0:/dev/obd'
    environment:
      - TZ=Europe/Oslo
    build:
      context: ./obd
      dockerfile: Dockerfile
    env_file:
      - secrets.env
    networks:
      - minusnet
  #################################################
  rclone:
    container_name: rclone
    restart: unless-stopped
    environment:
      - TZ=Europe/Oslo
    build:
      context: ./rclone
      dockerfile: Dockerfile
    volumes:
      - /home/minus/.config/rclone:/config/rclone # Must be configured on host
      - /home/minus/logs:/logs
    networks:
      - minusnet
  #################################################
  code-server:
    container_name: code-server
    restart: unless-stopped
    image: lscr.io/linuxserver/code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - DEFAULT_WORKSPACE=/dockervolumes
    ports:
      - '8443:8443'
    volumes:
      - '/home/minus/homeassistant_config:/dockervolumes/homeassistant_config'
      - '/home/minus/logs:/dockervolumes/logs'
    networks:
      - minusnet
  #################################################

networks:
  minusnet:
    driver: bridge
