# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 7
  commit_interval: 60

sensor:
  - platform: gpsd
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_temperature
      - type: processor_use
  - platform: command_line
    name: "Dennis present"
    command: "if find /logs/presence/*/Dennis.log -type f -mmin -1 &> /dev/null ; then echo true ; else echo false ; fi"
  - platform: command_line
    name: "Heidi present"
    command: "if find /logs/presence/*/Heidi.log -type f -mmin -1 &> /dev/null ; then echo true ; else echo false ; fi"
  - platform: command_line
    name: "Julie present"
    command: "if find /logs/presence/*/Julie.log -type f -mmin -1 &> /dev/null ; then echo true ; else echo false ; fi"
  - platform: command_line
    name: "Kevin present"
    command: "if find /logs/presence/*/Kevin.log -type f -mmin -1 &> /dev/null ; then echo true ; else echo false ; fi"

binary_sensor:
  - platform: ping
    host: 8.8.8.8
    name: "Internet"
    count: 4
    scan_interval: 10
