views:
  - theme: Backend-selected
    title: Home
    type: panel
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-filter
                entities:
                  - person.kevin
                  - person.heidi
                  - person.dennis
                  - person.julie
                state_filter:
                  - home
                card:
                  type: glance
                  show_icon: false
                  show_state: false
          - type: conditional
            conditions:
              - entity: binary_sensor.internet
                state: "on"
            card:
              show_current: true
              show_forecast: false
              type: weather-forecast
              entity: weather.home
          - type: horizontal-stack
            cards:
              - type: entity
                entity: sensor.gps
                icon: mdi:satellite-variant
              - type: conditional
                conditions:
                  - entity: binary_sensor.internet
                    state: "on"
                card:
                  type: entity
                  entity: sensor.local_ip
                  name: IP
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.processor_use
                name: CPU
                severity:
                  green: 0
                  yellow: 50
                  red: 75
              - type: gauge
                entity: sensor.processor_temperature
                name: CPU
                min: 1
                max: 75
                severity:
                  green: 20
                  yellow: 60
                  red: 70
              - type: gauge
                entity: sensor.memory_use_percent
                name: RAM
                severity:
                  green: 0
                  yellow: 50
                  red: 75
              - type: gauge
                entity: sensor.disk_use_percent
                name: Disk
                severity:
                  green: 0
                  yellow: 50
                  red: 75
title: Minus
