views:
  - theme: Backend-selected
    title: Home
    type: panel
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: conditional
                conditions:
                  - entity: sensor.gps
                    state: 3D Fix
                card:
                  type: entity
                  entity: sensor.gps
                  attribute: speed
                  unit: km/h
                  name: Speed
                  icon: mdi:satellite-variant
              - type: entity
                entity: sensor.soc
                name: SoC
                icon: mdi:battery
                unit: "%"
                state_color: false
          - type: horizontal-stack
            cards:
              - type: conditional
                conditions:
                  - entity: person.kevin
                    state: home
                card:
                  type: markdown
                  content: " "
                  title: Kevin
              - type: conditional
                conditions:
                  - entity: person.heidi
                    state: home
                card:
                  type: markdown
                  content: " "
                  title: Heidi
              - type: conditional
                conditions:
                  - entity: person.dennis
                    state: home
                card:
                  type: markdown
                  content: " "
                  title: Dennis
              - type: conditional
                conditions:
                  - entity: person.julie
                    state: home
                card:
                  type: markdown
                  content: " "
                  title: Julie
          - type: horizontal-stack
            cards:
              - type: entity
                entity: sensor.gps
                icon: mdi:satellite-variant
              - type: conditional
                conditions:
                  - entity: binary_sensor.internet
                    state: "on"
                card:
                  type: entity
                  entity: sensor.local_ip
                  name: IP
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.processor_use
                name: CPU
                severity:
                  green: 0
                  yellow: 50
                  red: 75
              - type: gauge
                entity: sensor.processor_temperature
                name: CPU
                min: 1
                max: 75
                severity:
                  green: 20
                  yellow: 60
                  red: 70
              - type: gauge
                entity: sensor.memory_use_percent
                name: RAM
                severity:
                  green: 0
                  yellow: 50
                  red: 75
              - type: gauge
                entity: sensor.disk_use_percent
                name: Disk
                severity:
                  green: 0
                  yellow: 50
                  red: 75
title: Minus
